### ISSUE TITLE
Player getting insta killed

### ISSUE THREAD

**Issue by GribixTugaZ** [NullSystemWorks/mtadayz#70] opened 2017-04-09 15:57 UTC
When a player creates an account gets insta killed. Right after the player registers,the "killed" screen will come.

**Comment by mtadayz** [comment] 2017-04-09 16:46
Can't confirm this happening on my server. I joined your server and noticed you have a modified login resource (I also got instakilled there). Maybe that's the cause?

**Comment by GribixTugaZ** [comment] 2017-04-09 20:26
Can be. Imma clean everything up and install everything clean.I used that new login panel and it worked just fine.Then i updated to the latest version,to get the latest fixes and that happened. Also.Before installing the newest version,i had my server all good and working flawlessly.From a sudden all the vehicle disappeared. Is this a know bug?

**Comment by mtadayz** [comment] 2017-04-09 20:30
It's...not supposed to happen, because no files were changed which relate to vehicles in any way. Perhaps you accidentally replaced your database?

**Comment by GribixTugaZ** [comment] 2017-04-09 20:36
I usually don't mess around with dbs.What if i delete the vehicles.db in DayZ/database . Will it automaticly create another one when i restart the server?

**Comment by mtadayz** [comment] 2017-04-11 15:31
No, you also have to delete the vehicleManager from the database (internal.db). You can do that by executing delaccount vehicleManager in the server console (note that you'll have to stop DayZ first).

**Comment by GribixTugaZ** [comment] 2017-04-11 18:21
Allright.I think i know what's wrong now.I've already used that command several other times and it ended up working.What i didn't do is stop DayZ before doing it. So.What i should do when this happens or before it happens is:

1- Stop DayZ
2- Do the command
3-Restart Server? Or start DayZ again?

**Comment by mtadayz** [comment] 2017-04-11 19:54
Start DayZ after you've deleted vehicleManager. The script will create a new one + vehicles too. Would replace the old vehicles.db with a new one, just to make sure it doesn't spawn new vehicles PLUS the ones already saved in the database. So basically:

1. Stop DayZ
2. Execute delaccount vehicleManager
3. Replace old vehicles.db with new one if necessary
4. Start DayZ

**Comment by GribixTugaZ** [comment] 2017-04-11 20:06
Done.Let's see if it solves the problem.Now one last thing before i close this topic.And sorry for getting out of the point. Why does the camera starts kinda of moving around from a sudden?Is it a feature or a bug? If it's a feature,is there anyway i can disable it?

**Comment by mtadayz** [comment] 2017-04-12 20:25
That happens when you are in pain. Originally, it was kind of a violent shake, but now we've added that camera sway. Suppose we could add it back and let server owners decide which one they like more.

**Comment by GribixTugaZ** [comment] 2017-04-12 20:34
Sounds nice. I would like to see some option for server owners to enable/disable and change the "shake". If needed i can start a issue about this just to let the other developers now.Thank you L. 👍 💯

**Comment by mtadayz** [comment] 2017-04-14 15:56
Added. I'll close this issue. If this bug reappears, feel free to create a new issue.

**Closed as completed by mtadayz** 2017-04-14 15:56 UTC
