### ISSUE TITLE
add armour vest cloth

### ISSUE THREAD

**Issue by ghost** [NullSystemWorks/mtadayz#163] opened 2018-03-14 09:51 UTC
Please add armour vest loot

**Comment by mtadayz** [comment] 2018-03-15 14:21
Duplicate of issue #114, closing this. Please stop opening the same issues over and over again just because you didn't receive a satisfying answer and your suggestion hasn't been implemented. It'll only serve to delay any progress.

**Closed as completed by mtadayz** 2018-03-15 14:21 UTC
